=== IstitutoCentraleCatalogoUnicoBiblio/SBNWeb-Open/SbnMarcEJB/ejbModule/it/finsiel/sbn/polo/factoring/init/properties.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:annotation>
		<xsd:documentation>
		Properties utilizzate in tutto il progetto indice
	</xsd:documentation>
	</xsd:annotation>
	<xsd:element name="proprieta">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="sezione_comune">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="SERVLET_INDICE_CONTROLLER" type="xsd:string"/>
							<xsd:element name="ICCU_TEST" type="xsd:string"/>
							<xsd:element name="ICCU_HOME" type="xsd:string"/>
							<xsd:element name="SIGLA_INDICE" type="xsd:string"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="sezione_naming">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="DEFAULT_DATASOURCE_JNDINAME" type="xsd:string"/>
							<xsd:element name="EMPTY_DATASOURCE_JNDINAME" type="xsd:string"/>
							<xsd:element name="TEST_DATASOURCE_JNDINAME" type="xsd:string"/>
							<xsd:element name="USERTRANSACTION_JNDINAME" type="xsd:string"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="sezione_box">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="USE_LDAP_FOR_BIS" type="xsd:string"/>
							<xsd:element name="LDAP_INITIAL_CONTEXT_FACTORY" type="xsd:string"/>
							<xsd:element name="LDAP_PROVIDER_URL" type="xsd:string"/>
							<xsd:element name="LDAP_SECURITY_AUTHENTICATION" type="xsd:string"/>
							<xsd:element name="LDAP_SECURITY_PRINCIPAL" type="xsd:string"/>
							<xsd:element name="LDAP_SECURITY_CREDENTIALS" type="xsd:string"/>
							<xsd:element name="LDAP_BIS_STORAGE_TIMEOUT" type="xsd:string"/>
							<xsd:element name="LDAP_BIS_DA_STORAGE_TIMEOUT" type="xsd:string"/>
							<xsd:element name="LDAP_BIS_DU_STORAGE_TIMEOUT" type="xsd:string"/>
							<xsd:element name="LDAP_BIS_PO_STORAGE_TIMEOUT" type="xsd:string"/>
							<xsd:element name="LDAP_BIS_SI_STORAGE_TIMEOUT" type="xsd:string"/>
							<xsd:element name="LDAP_BIS_SQ_STORAGE_TIMEOUT" type="xsd:string"/>
							<xsd:element name="LDAP_SBNMARC_STORAGE_TIMEOUT" type="xsd:string"/>
							<xsd:element name="LDAP_DIFFERITA_STORAGE_TIMEOUT" type="xsd:string"/>
							<xsd:element name="LDAP_GARBAGE_COLLECTOR_TIMEOUT" type="xsd:string"/>
							<xsd:element name="LDAP_MONITOR_STORAGE_TIMEOUT" type="xsd:string"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="sezione_bis">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="BIS_MAX_NUMERO_RECORD" type="xsd:string"/>
							<xsd:element name="BIS_MAX_NUMERO_FILE_OUTPUT" type="xsd:string"/>
							<xsd:element name="BIS_RIGHE_PER_FOGLIO" type="xsd:string"/>
							<xsd:element name="BIS_FOGLI_PER_FILE" type="xsd:string"/>
							<xsd:element name="BIS_RIGHE_PER_BLOCCO_SBNMARC" type="xsd:string"/>
							<xsd:element name="EXCEL_XSL_FILE" type="xsd:string"/>
							<xsd:element name="PDF_XSL_FILE" type="xsd:string"/>
							<xsd:element name="JSP_SCHEDULE_PER_PAGE" type="xsd:string"/>
							<xsd:element name="STARTNOW_DELAY_IN_MILLIS" type="xsd:string"/>
							<xsd:element name="MAX_CONCURRED_SCHEDULE" type="xsd:string"/>
							<xsd:element name="BIS_PARAMETRI_FILE" type="xsd:string"/>
							<xsd:element name="BIS_XML_BUFFER_CAPACITY" type="xsd:string"/>
							<xsd:element name="BIS_DIRECTORY_TEMPORANEA" type="xsd:string"/>
							<xsd:element name="BIS_DIRECTORY_INFORMAZIONI_DB" type="xsd:string"/>
							<xsd:element name="BIS_INFORMAZIONI_DB_MAX_NUMERO_RECORD" type="xsd:string"/>
							<xsd:element name="SCHEDULER_THREAD_TIMEOUT" type="xsd:string"/>
							<xsd:element name="SCHEDULER_LDAP_CHECK_TIMEOUT" type="xsd:string"/>
							<xsd:element name="BIS_ELABORA_SBNMARC" type="xsd:string"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="sezione_database">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="DB_DRIVER" type="xsd:string"/>
							<xsd:element name="DB_URL" type="xsd:string"/>
							<xsd:element name="DB_USER" type="xsd:string"/>
							<xsd:element name="DB_PASSWORD" type="xsd:string"/>
							<xsd:element name="DB_STAT_USER" type="xsd:string"/>
							<xsd:element name="DB_STAT_PASSWORD" type="xsd:string"/>
							<xsd:element name="DEFAULT_DS_URL" type="xsd:string"/>
							<xsd:element name="DB_IMPORT_USER" type="xsd:string"/>
							<xsd:element name="DB_IMPORT_PASSWORD" type="xsd:string"/>
							<xsd:element name="TEST_DS_URL" type="xsd:string"/>
							<xsd:element name="DB_IMPORT_T_USER" type="xsd:string"/>
							<xsd:element name="DB_IMPORT_T_PASSWORD" type="xsd:string"/>
							<xsd:element name="EMPTY_DS_URL" type="xsd:string"/>
							<xsd:element name="DB_IMPORT_E_USER" type="xsd:string"/>
							<xsd:element name="DB_IMPORT_E_PASSWORD" type="xsd:string"/>
							<xsd:element name="DB_CONN_NO" type="xsd:string"/>
							<xsd:element name="REMOVER_DELAY" type="xsd:string"/>
							<xsd:element name="REMOVER_TIMER" type="xsd:string"/>
							<!-- DEFAULT_DS: URL UTENTE E PSW per le operazioni di IMPORT -->
							<!-- TEST_DS: URL UTENTE E PSW per le operazioni di IMPORT -->
							<!-- EMPTY_DS: URL UTENTE E PSW per le operazioni di IMPORT -->
							<!-- Username e password per operazioni di import unimarc e marc21 DB DEFAULT -->
							<!-- Username e password per operazioni di import unimarc e marc21 DB TEST -->
							<!-- Username e password per operazioni di import unimarc e marc21 DB EMPTY -->
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="sezione_xml">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="PATH_XML_TAVOLE" type="xsd:string"/>
							<xsd:element name="FILE_XSD_TAVOLE" type="xsd:string"/>
							<xsd:element name="FILE_XML_ERRORI" type="xsd:string"/>
							<xsd:element name="FILE_XSD_ERRORI" type="xsd:string"/>
							<xsd:element name="FILE_XSD_SBNMARC" type="xsd:string"/>
							<xsd:element name="FILE_DOM_RESPONSE" type="xsd:string"/>
							<xsd:element name="SCHEMA_VERSION" type="xsd:string"/>
							<xsd:element name="SCHEMA_URL" type="xsd:string"/>
							<xsd:element name="FILE_XSD_TEST" type="xsd:string"/>
							<xsd:element name="FILE_XML_TEST" type="xsd:string"/>
							<xsd:element name="FILE_XSD_SCHEDULES" type="xsd:string"/>
							<xsd:element name="FILE_XML_SCHEDULES" type="xsd:string"/>
							<xsd:element name="FILE_XSD_JOBSCHEDULER" type="xsd:string"/>
							<xsd:element name="FILE_XML_JOBSCHEDULER" type="xsd:string"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="sezione_serversbnmarc">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="RIGHE_PER_BLOCCO_SBNMARC" type="xsd:string"/>
							<xsd:element name="NRO_MAX_GG_PER_RANGE_ALLINEA" type="xsd:string"/>
							<xsd:element name="NRO_MAX_CHIEDI_ALLINEA" type="xsd:string"/>
							<xsd:element name="RIGHE_PER_BLOCCO_ALLINEA" type="xsd:string"/>
							<xsd:element name="NRO_MAX_SPOSTAMENTO_LEGAMI" type="xsd:string"/>
							<xsd:element name="NRO_MAX_RIGHE_RICHIESTA" type="xsd:string"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="sezione_monitoraggio">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="ORA_AVVIO" type="xsd:string"/>
							<xsd:element name="NRO_MAX_OPERAZIONI_CONSECUTIVE" type="xsd:string"/>
							<xsd:element name="GAP_OPERAZIONI_CONSECUTIVE" type="xsd:string"/>
							<xsd:element name="NRO_MAX_OPERAZIONI_OUT_MEDIA" type="xsd:string"/>
							<xsd:element name="VALORE_MEDIO_LIMITE" type="xsd:string"/>
							<xsd:element name="NRO_MAX_OPERAZIONI" type="xsd:string"/>
							<xsd:element name="GAP_OPERAZIONI" type="xsd:string"/>
							<xsd:element name="NRO_MAX_RICHIESTE_ECCESSIVE" type="xsd:string"/>
							<xsd:element name="GAP_RICHIESTE_ECCESSIVE" type="xsd:string"/>
							<xsd:element name="MAX_VARIANZA_TEMPI_RISPOSTA" type="xsd:string"/>
							<xsd:element name="NUM_DAYS_BACKWARD_CHECK" type="xsd:string"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="sezione_test">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="TEST_XML_DB" type="xsd:string"/>
							<xsd:element name="TEST_XML_TEMP" type="xsd:string"/>
							<xsd:element name="TEST_XML_CORRETTI" type="xsd:string"/>
							<xsd:element name="TEST_XML_TEST" type="xsd:string"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="sezione_processi_differita">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="CONTENT_TYPE" type="xsd:string"/>
							<xsd:element name="FROM_ADDRESS" type="xsd:string"/>
							<xsd:element name="FROM_NAME" type="xsd:string"/>
							<xsd:element name="SERVICE_MAIL" type="xsd:string"/>
							<xsd:element name="ADMIN_MAIL" type="xsd:string"/>
							<xsd:element name="SMTP_HOST" type="xsd:string"/>
							<xsd:element name="TB_SCRIPT_MILLISECONDI_VITA" type="xsd:string"/>
							<xsd:element name="DIRECTORY_UPLOAD_DOWNLOAD" type="xsd:string"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="sezione_opac">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="GIORNI_ATTESA_EXPORT_OPAC" type="xsd:string"/>
							<xsd:element name="DIRECTORY_OPAC" type="xsd:string"/>
							<xsd:element name="DIRECTORY_OPAC_PERIODICO" type="xsd:string"/>
							<xsd:element name="FILE_INPUT_OPAC" type="xsd:string"/>
							<xsd:element name="NOME_FILE_BID_CANCELLATI" type="xsd:string"/>
							<xsd:element name="NOME_FILE_BID_FUSI" type="xsd:string"/>
							<xsd:element name="NOME_FILE_BID_VARIATI" type="xsd:string"/>
							<xsd:element name="NOME_FILE_BID_LOC_DA_CANC" type="xsd:string"/>
							<xsd:element name="NOME_FILE_UNIMARC_RIDOTTO" type="xsd:string"/>
							<xsd:element name="NOME_FILE_UNIMARC_OPAC" type="xsd:string"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== IstitutoCentraleCatalogoUnicoBiblio/SBNWeb-Open/SbnMarcEJB/ejbModule/it/finsiel/sbn/polo/factoring/init/properties.xml
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by carlo mangozzi (manane srl) --><proprieta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="properties.xsd">	<sezione_comune>		<SERVLET_INDICE_CONTROLLER>../../servlet/controller</SERVLET_INDICE_CONTROLLER>		<!--variabile>
        <PROJECT_PATH>/sbnmarc/</variabile-->		<ICCU_TEST>/sbnmarc/test-dati</ICCU_TEST>		<ICCU_HOME>/sbnmarc/</ICCU_HOME>		<SIGLA_INDICE>SBN</SIGLA_INDICE>	</sezione_comune>	<sezione_naming>		<DEFAULT_DATASOURCE_JNDINAME>SBNMarcDS</DEFAULT_DATASOURCE_JNDINAME>		<EMPTY_DATASOURCE_JNDINAME>empty_oraclePacsDS</EMPTY_DATASOURCE_JNDINAME>		<TEST_DATASOURCE_JNDINAME>test_oraclePacsDS</TEST_DATASOURCE_JNDINAME>		<USERTRANSACTION_JNDINAME>java:comp/UserTransaction</USERTRANSACTION_JNDINAME>	</sezione_naming>	<sezione_box>		<USE_LDAP_FOR_BIS>true</USE_LDAP_FOR_BIS>		<LDAP_INITIAL_CONTEXT_FACTORY>com.sun.jndi.ldap.LdapCtxFactory</LDAP_INITIAL_CONTEXT_FACTORY>		<!-- SBNMARC -->		<LDAP_PROVIDER_URL>ldap://192.168.20.75:389</LDAP_PROVIDER_URL>		<!-- SEBICCU -->		<!--LDAP_PROVIDER_URL>ldap://172.25.3.1:50389
    </LDAP_PROVIDER_URL-->		<LDAP_SECURITY_AUTHENTICATION>simple</LDAP_SECURITY_AUTHENTICATION>		<LDAP_SECURITY_PRINCIPAL>cn=Manager</LDAP_SECURITY_PRINCIPAL>		<LDAP_SECURITY_CREDENTIALS>ldap1pwd</LDAP_SECURITY_CREDENTIALS>		<LDAP_BIS_STORAGE_TIMEOUT>1296000000</LDAP_BIS_STORAGE_TIMEOUT>		<LDAP_BIS_DA_STORAGE_TIMEOUT>1296000000</LDAP_BIS_DA_STORAGE_TIMEOUT>		<LDAP_BIS_DU_STORAGE_TIMEOUT>1296000000</LDAP_BIS_DU_STORAGE_TIMEOUT>		<LDAP_BIS_PO_STORAGE_TIMEOUT>1296000000</LDAP_BIS_PO_STORAGE_TIMEOUT>		<LDAP_BIS_SI_STORAGE_TIMEOUT>1296000000</LDAP_BIS_SI_STORAGE_TIMEOUT>		<LDAP_BIS_SQ_STORAGE_TIMEOUT>1296000000</LDAP_BIS_SQ_STORAGE_TIMEOUT>		<LDAP_SBNMARC_STORAGE_TIMEOUT>1296000000</LDAP_SBNMARC_STORAGE_TIMEOUT>		<LDAP_DIFFERITA_STORAGE_TIMEOUT>7200000</LDAP_DIFFERITA_STORAGE_TIMEOUT>		<LDAP_GARBAGE_COLLECTOR_TIMEOUT>120000</LDAP_GARBAGE_COLLECTOR_TIMEOUT>		<LDAP_MONITOR_STORAGE_TIMEOUT>100000000</LDAP_MONITOR_STORAGE_TIMEOUT>	</sezione_box>	<sezione_bis>		<BIS_MAX_NUMERO_RECORD>8500000</BIS_MAX_NUMERO_RECORD>		<BIS_MAX_NUMERO_FILE_OUTPUT>12</BIS_MAX_NUMERO_FILE_OUTPUT>		<BIS_RIGHE_PER_FOGLIO>14</BIS_RIGHE_PER_FOGLIO>		<BIS_FOGLI_PER_FILE>260</BIS_FOGLI_PER_FILE>		<BIS_RIGHE_PER_BLOCCO_SBNMARC>100</BIS_RIGHE_PER_BLOCCO_SBNMARC>		<EXCEL_XSL_FILE>/sbnmarc/bis/bis2xls.xsl</EXCEL_XSL_FILE>		<PDF_XSL_FILE>/sbnmarc/bis/bis2pdf.xsl</PDF_XSL_FILE>		<JSP_SCHEDULE_PER_PAGE>8</JSP_SCHEDULE_PER_PAGE>		<STARTNOW_DELAY_IN_MILLIS>5000</STARTNOW_DELAY_IN_MILLIS>		<MAX_CONCURRED_SCHEDULE>5</MAX_CONCURRED_SCHEDULE>		<BIS_PARAMETRI_FILE>/sbnmarc/bis/bis_parametri.properties</BIS_PARAMETRI_FILE>		<BIS_XML_BUFFER_CAPACITY>3000000</BIS_XML_BUFFER_CAPACITY>		<BIS_DIRECTORY_TEMPORANEA>/sbnmarc/temp/bis/</BIS_DIRECTORY_TEMPORANEA>		<BIS_DIRECTORY_INFORMAZIONI_DB>/sbnmarc/temp/bis/</BIS_DIRECTORY_INFORMAZIONI_DB>		<BIS_INFORMAZIONI_DB_MAX_NUMERO_RECORD>1000000</BIS_INFORMAZIONI_DB_MAX_NUMERO_RECORD>		<SCHEDULER_THREAD_TIMEOUT>10000</SCHEDULER_THREAD_TIMEOUT>		<SCHEDULER_LDAP_CHECK_TIMEOUT>30000</SCHEDULER_LDAP_CHECK_TIMEOUT>		<BIS_ELABORA_SBNMARC>TRUE</BIS_ELABORA_SBNMARC>	</sezione_bis>	<sezione_database>		<DB_DRIVER>oracle.jdbc.driver.OracleDriver</DB_DRIVER>		<DB_URL>jdbc:oracle:thin:@10.30.1.30:4848:indice</DB_URL>		<!--
        <DB_URL>jdbc:oracle:thin:@172.24.96.8:1521:SBNMARC</DB_URL>-->		<!-- Username e password per il db da personalizzare -->		<DB_USER>sbnmarc</DB_USER>		<DB_PASSWORD>sbnmarc</DB_PASSWORD>		<!-- Username e password per operazioni di sistema su DB DEFAULT (area Monitoraggio/Statistiche)-->		<DB_STAT_USER>sbnmarc</DB_STAT_USER>		<DB_STAT_PASSWORD>sbnmarc</DB_STAT_PASSWORD>		<!-- DB DEFAULT URL di connessione per il DataBase di import unimarc e marc21 -->		<DEFAULT_DS_URL>jdbc:oracle:thin:@sebiccu.akros.it:1521:DBORICCU</DEFAULT_DS_URL>		<!-- DB DEFAULT Username e password per operazioni di import unimarc e marc21 -->		<DB_IMPORT_USER>FASEIMPORT</DB_IMPORT_USER>		<DB_IMPORT_PASSWORD>FASEIMPORT</DB_IMPORT_PASSWORD>		<!-- DB TEST URL di connessione per il DataBase di import unimarc e marc21 -->		<TEST_DS_URL>jdbc:oracle:thin:@sebiccu.akros.it:1521:DBORICCU</TEST_DS_URL>		<!-- DB TEST  Username e password per operazioni di import unimarc e marc21 -->		<DB_IMPORT_T_USER>FASEIMPORT</DB_IMPORT_T_USER>		<DB_IMPORT_T_PASSWORD>FASEIMPORT</DB_IMPORT_T_PASSWORD>		<!-- DB EMPTY URL di connessione per il DataBase di import unimarc e marc21 -->		<EMPTY_DS_URL>jdbc:oracle:thin:@172.24.96.8:1521:SBNMARC</EMPTY_DS_URL>		<!--DB EMPTY Username e password per operazioni di import unimarc e marc21  -->		<DB_IMPORT_E_USER>FASEIMPORT</DB_IMPORT_E_USER>		<DB_IMPORT_E_PASSWORD>FASEIMPORT</DB_IMPORT_E_PASSWORD>		<DB_CONN_NO>5</DB_CONN_NO>		<REMOVER_DELAY>1000</REMOVER_DELAY>		<REMOVER_TIMER>10000</REMOVER_TIMER>	</sezione_database>	<sezione_xml>		<PATH_XML_TAVOLE>/properties/xml/tavole</PATH_XML_TAVOLE>		<FILE_XSD_TAVOLE>/sbnmarc/properties/xml/tavole/StatementSql.xsd</FILE_XSD_TAVOLE>		<FILE_XML_ERRORI>/properties/xml/errori.xml</FILE_XML_ERRORI>		<FILE_XSD_ERRORI>/sbnmarc/properties/xml/errori.xsd</FILE_XSD_ERRORI>		<FILE_XSD_SBNMARC>/sbnmarc/conf/SBNMarcv100.xsd</FILE_XSD_SBNMARC>		<FILE_DOM_RESPONSE>/sbnmarc/logs/file_tree.xml</FILE_DOM_RESPONSE>		<SCHEMA_VERSION>1.12</SCHEMA_VERSION>		<SCHEMA_URL>http://sbnmarc.akros.it/indice/SBNMarcv109.xsd</SCHEMA_URL>		<FILE_XSD_TEST>/sbnmarc/test-dati/xml-db/testDB.xsd</FILE_XSD_TEST>		<FILE_XML_TEST>/sbnmarc/test-dati/xml-db/testDB.xml</FILE_XML_TEST>		<FILE_XSD_SCHEDULES>/sbnmarc/properties/xml/scheduler.xsd</FILE_XSD_SCHEDULES>		<FILE_XML_SCHEDULES>/sbnmarc/properties/xml/scheduler.xml</FILE_XML_SCHEDULES>		<FILE_XSD_JOBSCHEDULER>/sbnmarc/properties/xml/JobScheduler.xsd</FILE_XSD_JOBSCHEDULER>		<FILE_XML_JOBSCHEDULER>/sbnmarc/properties/xml/JobScheduler.xml</FILE_XML_JOBSCHEDULER>	</sezione_xml>	<sezione_serversbnmarc>		<RIGHE_PER_BLOCCO_SBNMARC>10</RIGHE_PER_BLOCCO_SBNMARC>		<NRO_MAX_GG_PER_RANGE_ALLINEA>10</NRO_MAX_GG_PER_RANGE_ALLINEA>		<NRO_MAX_CHIEDI_ALLINEA>10</NRO_MAX_CHIEDI_ALLINEA>		<RIGHE_PER_BLOCCO_ALLINEA>10</RIGHE_PER_BLOCCO_ALLINEA>		<NRO_MAX_SPOSTAMENTO_LEGAMI>10</NRO_MAX_SPOSTAMENTO_LEGAMI>		<NRO_MAX_RIGHE_RICHIESTA>10</NRO_MAX_RIGHE_RICHIESTA>	</sezione_serversbnmarc>	<sezione_monitoraggio>		<ORA_AVVIO>20:30</ORA_AVVIO>		<NRO_MAX_OPERAZIONI_CONSECUTIVE>30</NRO_MAX_OPERAZIONI_CONSECUTIVE>		<GAP_OPERAZIONI_CONSECUTIVE>60</GAP_OPERAZIONI_CONSECUTIVE>		<NRO_MAX_OPERAZIONI_OUT_MEDIA>10</NRO_MAX_OPERAZIONI_OUT_MEDIA>		<VALORE_MEDIO_LIMITE>10</VALORE_MEDIO_LIMITE>		<NRO_MAX_OPERAZIONI>50</NRO_MAX_OPERAZIONI>		<GAP_OPERAZIONI>60</GAP_OPERAZIONI>		<NRO_MAX_RICHIESTE_ECCESSIVE>10</NRO_MAX_RICHIESTE_ECCESSIVE>		<GAP_RICHIESTE_ECCESSIVE>3600</GAP_RICHIESTE_ECCESSIVE>		<MAX_VARIANZA_TEMPI_RISPOSTA>1</MAX_VARIANZA_TEMPI_RISPOSTA>		<NUM_DAYS_BACKWARD_CHECK>20</NUM_DAYS_BACKWARD_CHECK>	</sezione_monitoraggio>	<sezione_test>		<TEST_XML_DB>xml-db</TEST_XML_DB>		<TEST_XML_TEMP>xml-temp</TEST_XML_TEMP>		<TEST_XML_CORRETTI>xml-corretti</TEST_XML_CORRETTI>		<TEST_XML_TEST>xml-test</TEST_XML_TEST>	</sezione_test>	<sezione_processi_differita>		<CONTENT_TYPE>text/plain</CONTENT_TYPE>		<FROM_ADDRESS>SBNMarc@iccu.sbn.it</FROM_ADDRESS>		<FROM_NAME>Server Indice SBNMarc</FROM_NAME>		<SERVICE_MAIL>mail/SbnmarcMailer</SERVICE_MAIL>		<ADMIN_MAIL>tragazzini@akros.it</ADMIN_MAIL>		<SMTP_HOST>localhost</SMTP_HOST>		<TB_SCRIPT_MILLISECONDI_VITA>1209600000</TB_SCRIPT_MILLISECONDI_VITA>		<DIRECTORY_UPLOAD_DOWNLOAD>/sbnmarc/temp</DIRECTORY_UPLOAD_DOWNLOAD>	</sezione_processi_differita>	<sezione_opac>		<GIORNI_ATTESA_EXPORT_OPAC>7</GIORNI_ATTESA_EXPORT_OPAC>		<DIRECTORY_OPAC>/sbnmarc/opac</DIRECTORY_OPAC>		<DIRECTORY_OPAC_PERIODICO>/sbnmarc/opac</DIRECTORY_OPAC_PERIODICO>		<FILE_INPUT_OPAC>/sbnmarc/properties/xml/exportopac.xml</FILE_INPUT_OPAC>		<NOME_FILE_BID_CANCELLATI>TITOLI_CANCELLATI</NOME_FILE_BID_CANCELLATI>		<NOME_FILE_BID_FUSI>TITOLI_FUSI</NOME_FILE_BID_FUSI>		<NOME_FILE_BID_VARIATI>TITOLI_VARIATI</NOME_FILE_BID_VARIATI>		<NOME_FILE_BID_LOC_DA_CANC>TITOLI_LOC_DA_CANC</NOME_FILE_BID_LOC_DA_CANC>		<NOME_FILE_UNIMARC_RIDOTTO>TITOLI_UNIMARC_RIDOTTO</NOME_FILE_UNIMARC_RIDOTTO>		<NOME_FILE_UNIMARC_OPAC>TITOLI_UNIMARC</NOME_FILE_UNIMARC_OPAC>	</sezione_opac></proprieta>
