=== IstitutoCentraleCatalogoUnicoBiblio/SBNWeb-Open/SbnMarcEJB/ejbModule/META-INF/errori/errori.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:annotation>
		<xsd:documentation>
			Descrizione degli errori
		</xsd:documentation>
	</xsd:annotation>
	<xsd:element name="Errori">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="referente_default">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="nome_ref_def" type="xsd:string"/>
							<xsd:element name="mail_ref_def" type="xsd:string"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Errore" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="nota" type="xsd:string" minOccurs="0"/>
							<xsd:element name="descrizione" type="xsd:string"/>
							<xsd:element name="referente" minOccurs="0">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="nome" type="xsd:string"/>
										<xsd:element name="mail" type="xsd:string" minOccurs="0"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="id" type="xsd:int" use="required"/>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== IstitutoCentraleCatalogoUnicoBiblio/SBNWeb-Open/SbnMarcEJB/ejbModule/META-INF/errori/errori.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (C) 2019 ICCU - Istituto Centrale per il Catalogo Unico
  
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published
  by the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.
  
  You should have received a copy of the GNU Affero General Public License
  along with this program. If not, see <http://www.gnu.org/licenses/>.
-->
<Errori xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="errori.xsd">
	<referente_default>
		<nome_ref_def>Referente di default</nome_ref_def>
		<mail_ref_def>default@sbnweb.iccu.it</mail_ref_def>
	</referente_default>
	<Errore id="-1">
		<descrizione>
			Errore privo di descrizione
		</descrizione>
	</Errore>
	<Errore id="20">
		<descrizione>L'esecuzione necessita il rollback</descrizione>
	</Errore>
	<Errore id="54">
		<descrizione>errore nel salvataggio della sessione</descrizione>
	</Errore>
	<Errore id="55">
		<descrizione>LOADING PARSER ERROR: Dynamic lookup failed - </descrizione>
	</Errore>
	<Errore id="56">
		<descrizione>Errore interno all'applicazione</descrizione>
	</Errore>
	<Errore id="70">
		<descrizione>Non è stato possibile schedulare correttamente la richiesta</descrizione>
	</Errore>
	<Errore id="100">
		<descrizione>Errore durante il trattamento di input XML</descrizione>
	</Errore>
	<Errore id="101">
		<descrizione>Errore di marshalling XML</descrizione>
	</Errore>
	<Errore id="102">
		<descrizione>File XML inesistente</descrizione>
	</Errore>
	<Errore id="103">
		<descrizione>Errore: character encoding della richiesta non UTF-8</descrizione>
	</Errore>
	<Errore id="200">
		<descrizione>Errore: oggetto tavola_response null</descrizione>
	</Errore>
	<Errore id="201">
		<descrizione>Errore: tipologia di ricerca errata</descrizione>
	</Errore>
	<Errore id="202">
		<nota>Errore temporaneo</nota>
		<descrizione>Errore occorso durante l'accesso al DB</descrizione>
	</Errore>
	<Errore id="210">
		<descrizione>Server LDAP non funzionante, contattare l'amministratore del CED ICCU.</descrizione>
	</Errore>
	<Errore id="300">
		<nota>Eccezione in CreaAttivita.executeFactoring()</nota>
		<descrizione>Un' attività con questa descrizione esiste già</descrizione>
	</Errore>
	<Errore id="301">
		<nota>Eccezione in CreaGruppo.executeFactoring()</nota>
		<descrizione>Un gruppo con questa descrizione esiste già</descrizione>
	</Errore>
	<Errore id="302">
		<nota>Eccezione in DisabilitaUtente.executeFactoring()</nota>
		<descrizione>Errore invocazione DisabilitaUtente: manca un parametro </descrizione>
	</Errore>
	<Errore id="303">
		<nota>Eccezione in RicercaUtente.getResult()</nota>
		<descrizione>Parametro utente mancante</descrizione>
	</Errore>
	<Errore id="400">
		<descrizione>Attivita non esistente</descrizione>
	</Errore>
	<Errore id="401">
		<descrizione>Gruppo non esistente</descrizione>
	</Errore>
	<Errore id="402">
		<descrizione>Attivita o utente non esistente</descrizione>
	</Errore>
	<Errore id="403">
		<descrizione>Il gruppo padre non esiste in memoria</descrizione>
	</Errore>
	<Errore id="404">
		<descrizione>L'attivita non esiste in memoria</descrizione>
	</Errore>
	<Errore id="405">
		<descrizione>L'attivita o l'utente non esistono in memoria</descrizione>
	</Errore>
	<Errore id="406">
		<descrizione>Il gruppo figlio non esiste in memoria</descrizione>
	</Errore>
	<Errore id="407">
		<descrizione>L'inserimento della relazione introdurrebbe un ciclo nella gerarchia dei gruppi</descrizione>
	</Errore>
	<Errore id="408">
		<descrizione>Confronto fra gruppi nulli</descrizione>
	</Errore>
	<Errore id="409">
		<descrizione>Gruppo o utente non esistono in memoria</descrizione>
	</Errore>
	<Errore id="410">
		<descrizione>L' utente non esiste in memoria</descrizione>
	</Errore>
	<Errore id="411">
		<descrizione>Formato data non previsto</descrizione>
	</Errore>
	<Errore id="412"> <!-- almaviva7 05/05/2014  -->
		<descrizione>Data Da e Data A con carattere jolly non coincidono</descrizione>
	</Errore>
	<Errore id="500">
		<descrizione>Operazione eseguita: è possibile scaricare i file</descrizione>
	</Errore>
	<Errore id="501">
		<descrizione>Funzionalità non implementata</descrizione>
	</Errore>
	<!--Errori legati ad operazioni sul database -->
	<Errore id="1001">
		<descrizione>
			Errore generico occorso durante l'accesso al DB
		</descrizione>
	</Errore>
	<Errore id="1002">
		<descrizione>ERRORE SQL CONNESSIONE DB</descrizione>
	</Errore>
	<Errore id="1003">
		<descrizione>ERRORE PROGRAM CONNESSIONE DB</descrizione>
	</Errore>
	<Errore id="1004">
		<descrizione>ERRORE SQL TEST CONNESSIONE DB</descrizione>
	</Errore>
	<Errore id="1005">
		<descrizione>ERRORE PROGRAM TEST CONNESSIONE DB</descrizione>
	</Errore>
	<Errore id="1001">
		<descrizione>ERRORE SQL COMMIT VERSO IL DBASE</descrizione>
	</Errore>
	<Errore id="1006">
		<descrizione>ERRORE SQL CLOSE CONNESSIONE DB</descrizione>
	</Errore>
	<Errore id="1007">
		<descrizione>ERRORE SQL ROLLBACK VERSO IL DBASE</descrizione>
	</Errore>
	<Errore id="1051">
		<descrizione>ERRORE CREAZIONE STATEMENT SQL </descrizione>
	</Errore>
	<Errore id="1050">
		<descrizione>Si è verificato un errore nell'accesso al database</descrizione>
	</Errore>
	<Errore id="1103">
		<descrizione>(DSRICHINFO) ERRORE OPERAZIONE SQL</descrizione>
	</Errore>
	<Errore id="1151">
		<descrizione>(SELECT CHIAVE PRIMARIA) ERRORE OPERAZIONE SQL</descrizione>
	</Errore>
	<Errore id="1200">
		<descrizione>Dummy Error</descrizione>
	</Errore>
	<!--Errori legati ad EccezioneDB -->
	<Errore id="1202">
		<descrizione>Errore occorso durante l'accesso al DB: elemento già presente nella tavola</descrizione>
	</Errore>
	<Errore id="1203">
		<descrizione>Errore nella lettura da Database.</descrizione>
	</Errore>
	<Errore id="1204">
		<descrizione>Errore nella sequence del database</descrizione>
	</Errore>
	<Errore id="1210">
		<descrizione>	Campo non trovato nel result set.</descrizione>
	</Errore>
	<Errore id="1220">
		<descrizione>
			La commit non può essere eseguita.
		</descrizione>
	</Errore>
	<Errore id="1230">
		<descrizione>Errore nella creazione dello statement SQL</descrizione>
	</Errore>
	<Errore id="1231">
		<descrizione>Errore nella creazione dell'ordinamento SQL</descrizione>
	</Errore>
	<!-- Fine errori legati ad EccezioneDB -->
	<Errore id="2003">
		<descrizione>Errore di analisi</descrizione>
	</Errore>
	<Errore id="2004">
		<descrizione>Errore di lettura Uri</descrizione>
	</Errore>
	<Errore id="2001">
		<descrizione>Errore di castor validator</descrizione>
	</Errore>
	<Errore id="2002">
		<descrizione>Errore di marshalling</descrizione>
	</Errore>
	<Errore id="894">
		<descrizione>unmarshal PARSER ERROR: In root object</descrizione>
	</Errore>
	<!-- Errori diagnostici legati alle eccezioni EccezioneSbnDiagnostico -->
	<Errore id="0">
		<descrizione>
			Operazione eseguita correttamente
		</descrizione>
	</Errore>
	<Errore id="3001">
		<descrizione>
			Nessun elemento trovato
		</descrizione>
	</Errore>
	<Errore id="3002">
		<descrizione>
			Elaborazione registrata in coda
		</descrizione>
	</Errore>
	<Errore id="3003">
		<descrizione>
			La ricerca seleziona troppi elementi: restringere le condizioni
		</descrizione>
	</Errore>
	<Errore id="3004">
		<descrizione>
			Esistono elementi simili
		</descrizione>
	</Errore>
	<Errore id="3005">
		<descrizione>
			Errore: Utente non abilitato all'uso dell'attività
		</descrizione>
	</Errore>
	<Errore id="3006">
		<descrizione>
			Errore: Livello di autorità non autorizzato all'Utente
		</descrizione>
	</Errore>
	<Errore id="3007">
		<descrizione>
			Errore: Livello di autorità dell'utente non consente l'operazione
		</descrizione>
	</Errore>
	<Errore id="3008">
		<descrizione>
			Errore: Utente non abilitato a forzare la correzione
		</descrizione>
	</Errore>
	<Errore id="3009">
		<descrizione>
			Errore: Utente non abilitato alla gestione del tipo Authority
		</descrizione>
	</Errore>
	<Errore id="3010">
		<descrizione>
			Errore: il livello di autorità sulla base dati è superiore a quello comunicato
		</descrizione>
	</Errore>
	<Errore id="3011">
		<descrizione>
			Errore: Tipo di controllo simili inesistente
		</descrizione>
	</Errore>
	<Errore id="3012">
		<descrizione>
			Errore: Identificativo già esistente in base dati
		</descrizione>
	</Errore>
	<Errore id="3013">
		<descrizione>
			Errore: L'identificativo non esiste in base dati
		</descrizione>
	</Errore>
	<Errore id="3014">
		<descrizione>
			Errore: la data di ultima variazione non coincide con quella registrata in base dati
		</descrizione>
	</Errore>
	<Errore id="3015">
		<descrizione>
			Errore: dato codificato inesistente
		</descrizione>
	</Errore>
	<Errore id="3016">
		<descrizione>
			Errore: almeno una citazione è obbligatoria per la marca
		</descrizione>
	</Errore>
	<Errore id="3017">
		<descrizione>
			Errore: manca l'informazione di versione T005
		</descrizione>
	</Errore>
	<Errore id="3018">
		<descrizione>
			Errore: troppi parametri valorizzati
		</descrizione>
	</Errore>
	<Errore id="3019">
		<descrizione>
			Errore: almeno una parola chiave è obbligatoria per la marca
		</descrizione>
	</Errore>
	<Errore id="3020">
		<descrizione>
			Errore: almeno un legame a repertorio è obbligatorio per la marca
		</descrizione>
	</Errore>
	<Errore id="3021">
		<descrizione>
			Errore: si accettano al massimo 5 parole per la marca
		</descrizione>
	</Errore>
	<Errore id="3022">
		<descrizione>
			Errore: autore da collegare inesistente
		</descrizione>
	</Errore>
	<Errore id="3023">
		<descrizione>
			Errore: repertorio da collegare inesistente
		</descrizione>
